name: Build Docker Image for Build branch with VPN

on:
  push:
    branches:
      - build

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image for Build branch
        run: |
          docker build -f Dockerfiles/Dockerfile.build -t listprojects-build .
          docker tag listprojects-build ${{ secrets.DOCKER_USERNAME }}/listprojects:build
          docker push ${{ secrets.DOCKER_USERNAME }}/listprojects:build

      - name: SSH to server and update Build container with VPN
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /home/sshuser/sitegit
            git pull origin build

            docker pull ${{ secrets.DOCKER_USERNAME }}/listprojects:build

            docker stop build-site-container || true
            docker rm build-site-container || true

            docker run -d -p 8082:8082 --name build-site-container \
              -v /home/sshuser/vpn-data:/vpn-data \
              -v /home/sshuser/sitegit/Dockerfiles/nginxconfig/nginx-build.conf:/etc/nginx/nginx.conf \
              -v /home/sshuser/sitegit:/usr/share/nginx/html \
              --cap-add=NET_ADMIN \
              ${{ secrets.DOCKER_USERNAME }}/listprojects:build

            docker exec build-site-container nginx -s reload