name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker build -t listprojects .

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Tag Docker image
      run: |
        docker tag listprojects ${{ secrets.DOCKER_USERNAME }}/listprojects:latest

    - name: Push Docker image to DockerHub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/listprojects:latest

    - name: SSH to server and update Docker container
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          cd /home/sshuser/sitegit
          git pull

          # docker pull ${{ secrets.DOCKER_USERNAME }}/listprojects:latest
          
          # docker stop my-site-container || true
          # docker rm my-site-container || true

          # docker run -d -p 80:80 --name my-site-container \
          #   -v /home/sshuser/sitegit/nginx.conf:/etc/nginx/nginx.conf \
          #   -v /home/sshuser/sitegit:/usr/share/nginx/html \
          #   ${{ secrets.DOCKER_USERNAME }}/listprojects:latest

          # docker exec my-site-container nginx -s reload

          docker stop my-site-container || true
          docker rm my-site-container || true
          docker stop nginx-proxy || true
          docker rm nginx-proxy || true
          docker stop acme-companion || true
          docker rm acme-companion || true

          docker run -d --name nginx-proxy \
            -p 80:80 -p 443:443 \
            -v /var/run/docker.sock:/tmp/docker.sock:ro \
            -v /etc/nginx/certs:/etc/nginx/certs \
            -v /etc/nginx/vhost.d:/etc/nginx/vhost.d \
            -v /usr/share/nginx/html:/usr/share/nginx/html \
            jwilder/nginx-proxy

          docker run -d --name acme-companion \
            --volumes-from nginx-proxy \
            -v /var/run/docker.sock:/var/run/docker.sock:ro \
            nginxproxy/acme-companion

          docker run -d --name my-site-container \
            --expose 80 \
            -e VIRTUAL_HOST=nikitaredko.ru,www.nikitaredko.ru \
            -e LETSENCRYPT_HOST=nikitaredko.ru,www.nikitaredko.ru \
            -e LETSENCRYPT_EMAIL=your-email@example.com \
            ${{ secrets.DOCKER_USERNAME }}/listprojects:latest
