name: Build Docker Image for Build branch with VPN

on:
  push:
    branches:
      - build

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image for Build branch with VPN
        run: |
          docker build -f Dockerfile.vpn -t listprojects-build .  # Сборка с VPN
          docker tag listprojects-build ${{ secrets.DOCKER_USERNAME }}/listprojects:build
          docker push ${{ secrets.DOCKER_USERNAME }}/listprojects:build

      - name: SSH to server and update Build container with VPN
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /home/sshuser/sitegit || git clone https://github.com/crazykivi/my-site.git /home/sshuser/sitegit
            git checkout build
            git pull origin build

            mkdir -p /home/sshuser/vpn-data
            chmod -R 777 /home/sshuser/vpn-data

            if [ ! -f /home/sshuser/vpn-data/config.ovpn ]; then
              echo "Создаём базовую конфигурацию VPN..."
              echo "client" > /home/sshuser/vpn-data/config.ovpn
              echo "dev tun" >> /home/sshuser/vpn-data/config.ovpn
              echo "proto udp" >> /home/sshuser/vpn-data/config.ovpn
              echo "remote vpn.example.com 1194" >> /home/sshuser/vpn-data/config.ovpn
              echo "resolv-retry infinite" >> /home/sshuser/vpn-data/config.ovpn
              echo "nobind" >> /home/sshuser/vpn-data/config.ovpn
              echo "persist-key" >> /home/sshuser/vpn-data/config.ovpn
              echo "persist-tun" >> /home/sshuser/vpn-data/config.ovpn
              echo "ca /vpn-data/ca.crt" >> /home/sshuser/vpn-data/config.ovpn
              echo "cert /vpn-data/client.crt" >> /home/sshuser/vpn-data/config.ovpn
              echo "key /vpn-data/client.key" >> /home/sshuser/vpn-data/config.ovpn
              echo "remote-cert-tls server" >> /home/sshuser/vpn-data/config.ovpn
              echo "cipher AES-256-CBC" >> /home/sshuser/vpn-data/config.ovpn
              echo "verb 3" >> /home/sshuser/vpn-data/config.ovpn
            fi

            docker pull ${{ secrets.DOCKER_USERNAME }}/listprojects:build

            docker stop build-site-container || true
            docker rm build-site-container || true

            docker run -d -p 8082:8082 --name build-site-container \
              -v /home/sshuser/vpn-data:/vpn-data \
              -v /home/sshuser/sitegit/nginxconfig/nginx-build.conf:/etc/nginx/nginx.conf \
              -v /home/sshuser/sitegit:/usr/share/nginx/html \
              --cap-add=NET_ADMIN \
              ${{ secrets.DOCKER_USERNAME }}/listprojects:build

            docker exec build-site-container nginx -s reload
