name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main
      - build

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image for Main branch
        if: github.ref == 'refs/heads/main'
        run: |
          docker build -t listprojects-main .
          docker tag listprojects-main ${{ secrets.DOCKER_USERNAME }}/listprojects:main
          docker push ${{ secrets.DOCKER_USERNAME }}/listprojects:main

      - name: Build Docker image for Build branch with VPN
        if: github.ref == 'refs/heads/build'
        run: |
          docker build -f Dockerfile.vpn -t listprojects-build .
          docker tag listprojects-build ${{ secrets.DOCKER_USERNAME }}/listprojects:build
          docker push ${{ secrets.DOCKER_USERNAME }}/listprojects:build

      - name: SSH to server and update Main container
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/listprojects:main

            docker stop main-site-container || true
            docker rm main-site-container || true

            docker run -d -p 8080:8080 --name main-site-container \
              -v /home/sshuser/sitegit/nginx-main.conf:/etc/nginx/nginx.conf \
              -v /home/sshuser/sitegit:/usr/share/nginx/html \
              ${{ secrets.DOCKER_USERNAME }}/listprojects:main

            docker exec main-site-container nginx -s reload

      - name: SSH to server and update Build container with VPN
        if: github.ref == 'refs/heads/build'
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            mkdir -p /home/sshuser/vpn-data

            if [ ! -f /home/sshuser/vpn-data/config.ovpn ]; then
              echo "Создаём базовую конфигурацию VPN..."
              cat > /home/sshuser/vpn-data/config.ovpn <<EOL
client
dev tun
proto udp
remote vpn.example.com 1194
resolv-retry infinite
nobind
persist-key
persist-tun
ca /vpn-data/ca.crt
cert /vpn-data/client.crt
key /vpn-data/client.key
remote-cert-tls server
cipher AES-256-CBC
verb 3
EOL
              touch /home/sshuser/vpn-data/ca.crt
              touch /home/sshuser/vpn-data/client.crt
              touch /home/sshuser/vpn-data/client.key
            fi

            docker pull ${{ secrets.DOCKER_USERNAME }}/listprojects:build

            docker stop build-site-container || true
            docker rm build-site-container || true

            docker run -d -p 8082:8082 --name build-site-container \
              -v /home/sshuser/vpn-data:/vpn-data \
              -v /home/sshuser/sitegit/nginx-build.conf:/etc/nginx/nginx.conf \
              -v /home/sshuser/sitegit:/usr/share/nginx/html \
              --cap-add=NET_ADMIN \
              ${{ secrets.DOCKER_USERNAME }}/listprojects:build

            docker exec build-site-container nginx -s reload
