name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -f Dockerfiles/Dockerfile -t mysite .

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag Docker image
        run: |
          docker tag mysite ${{ secrets.DOCKER_USERNAME }}/mysite:latest

      - name: Push Docker image to DockerHub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/mysite:latest

      - name: SSH to server and update Docker container
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/sshuser/sitegit
            git pull || echo "Git pull failed"

            docker pull ${{ secrets.DOCKER_USERNAME }}/mysite:latest

            docker stop my-site-container || true
            docker rm my-site-container || true

            docker run -d -p 8080:8080 --name my-site-container \
              -v /home/sshuser/sitegit/Dockerfiles/nginxconfig/nginx-main.conf:/etc/nginx/nginx.conf \
              -v /home/sshuser/sitegit:/usr/share/nginx/html \
              ${{ secrets.DOCKER_USERNAME }}/mysite:latest

            docker exec my-site-container nginx -s reload